# Generated by Django 5.0 on 2023-12-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='QuoteForm',
        ),
    ]
