# Generated by Django 5.0 on 2023-12-28 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_server_quoteform'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
